### ISSUE TITLE
Error to open symbolic link

### ISSUE THREAD

**Issue by JonathanCosta** [devlinx9/muon-ssh#38]
**Describe the bug**
When trying to access a symbolic link, the error "net.schmizz.sshj.sftp.SFTPException: No such file" is displayed.

**To Reproduce**
1. navigate to a directory that contains a symbolic link
2. Click to open  symbolic link
3. See error

**Expected behavior**
The file would open, or would the directory open

**Comment by devlinx9** [comment]
Resolved in release 2.1.0
