### ISSUE TITLE
Latest .exe and .jar builds fail to open on Windows

### ISSUE THREAD

**Issue by oiseaumanifesto** [devlinx9/muon-ssh#53]
Hello! I attempted to download and install the latest release, however both the .exe and the .jar fail to work.

**The Issue**
The .exe, even when run with administrator privileges, only opens https://java.com/en/download/ in my browser and nothing more. I installed the the latest version of Java and restarted my machine, but this behaviour does not change.

The .jar will not open. It exits with error "Error: A JNI error has occurred, check your installation and try again".

**Versions**
- OS: Windows Home Edition 20H2, OSBuild 19042.1415
- Java: Version 8 Build 311

**Comment by devlinx9** [comment]
The software is build on Java 11, you're absolutely right about this issue, here is a workaround for this (while I'm working on the windows build) you have to download the 11 version of jdk: https://www.oracle.com/java/technologies/downloads/#java11-windows
